### ISSUE TITLE
template files not found on client

### ISSUE THREAD

**Issue by mtbvang** [Karnith/sails-generate-angular-gulp#24]
Hi,

I went through the setup and on going to the home page I get two errors on the developer tools console. When I check in the source tab I see that the src/app/home and header folders only contains a index.js file. On the server the index.tpl.html file is in the .tmp/public/src/app/home and header folders. So is this error happening because the index.tpl.html file should be on the client side too and if so why isn't it being sent over when it's in .tmp folder?

GET http://localhost:1351/header/index.tpl.html 404 (Not Found)(anonymous function) @ angular.js:9902sendReq @ angular.js:9703$get.serverRequest @ angular.js:9415processQueue @ angular.js:13292(anonymous function) @ angular.js:13308$get.Scope.$eval @ angular.js:14547$get.Scope.$digest @ angular.js:14363$get.Scope.$apply @ angular.js:14652bootstrapApply @ angular.js:1458invoke @ angular.js:4219doBootstrap @ angular.js:1456bootstrap @ angular.js:1476angularInit @ angular.js:1370(anonymous function) @ angular.js:26419trigger @ angular.js:2773eventHandler @ angular.js:3047

GET http://localhost:1351/home/index.tpl.html 404 (Not Found)(anonymous function) @ angular.js:9902sendReq @ angular.js:9703$get.serverRequest @ angular.js:9415processQueue @ angular.js:13292(anonymous function) @ angular.js:13308$get.Scope.$eval @ angular.js:14547$get.Scope.$digest @ angular.js:14363$get.Scope.$apply @ angular.js:14652bootstrapApply @ angular.js:1458invoke @ angular.js:4219doBootstrap @ angular.js:1456bootstrap @ angular.js:1476angularInit @ angular.js:1370(anonymous function) @ angular.js:26419trigger @ angular.js:2773eventHandler @ angular.js:3047

**Comment by mtbvang** [comment]
Figured it out. The templateURL in assets/src/home/index.js is wrong. Changed it to templateUrl: 'src/app/about/index.tpl.html'. Also did the same for the other index.js files.

The views/home/index.ejs file ln 20 also need the path updated to 'src/app/header/index.tpl.html'.

What's the best course of action to fix the generator?

**Comment by Karnith** [comment]
Hi,

I will be doing a massive check and update of all the generators once socket.io and engine.io fix their compile issue involving ws.


-------- Original message --------

**Comment by hansiemithun** [comment]
Hi, I am not able to get this up due to the following error. Throws grunt error as well as gulp error. Gulp error as: 

`Gulp :: 
error: Gulp :: TypeError: Property 'compileAssets' of object #<Object> is not a function
    at invokeConfigFn (/var/www/html/crs/gulpfile.js:69:20)
    at Object.<anonymous> (/var/www/html/crs/gulpfile.js:88:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/var/www/html/crs/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/var/www/html/crs/node_modules/gulp/node_modules/liftoff/index.js:193:16)`

>  I am running on sails version : 0.12

I already had sails installed in my system: I created a app using: sails new crs. Inside crs i added .sailsrc file and added the generators which were required as mentioned in readme that would finally look like: 

`
{
    "generators": {
        "modules": {
            "new": "sails-generate-new-gulp",
            "frontend": "sails-generate-frontend-gulp",
            "backend": "sails-generate-backend-gulp",
            "gulpfile": "sails-generate-gulpfile",
            "bower": "sails-generate-bower-gulp",
            "angular": "sails-generate-angular-gulp"
        }
    }
}
`
So after this i changed **jsfilesinject** as well in pipeline.js. Later when i installed generators like bower and angular in my project. Later when i try to ran sails lift, its throwing error as such. Kindly help me at the earliest to kickstart with my project or i have to scaffold a different one as i am in a critical situation.

Thanks in advance

**Comment by Karnith** [comment]
This module is no longer developed. Please use machinepack-sailsgulpify https://github.com/Karnith/machinepack-sailsgulpify
